### ISSUE TITLE
Add operationName audit to the graphql-http-test

### ISSUE THREAD

**Issue by sjparsons** [graphql/graphql-over-http#113]
When GraphQL queries contain more than one operation, then an operationName should be present in the payload body. Need to add an audit for this case. 

https://github.com/jaydenseric/graphql-http-test

@jaydenseric I'm adding this an issue here, if you want to also reference an issue on your repo that'd be cool.

**Comment by benjie** [comment]
s/should/must

**Comment by spawnia** [comment]
*As the group increasingly radicalized, countless instances of should were being replaced with must.* 😉

**Comment by benjie** [comment]
This is really something covered by the GraphQL spec itself:

- https://spec.graphql.org/June2018/#GetOperation()
- https://spec.graphql.org/June2018/#sec-Operation-Name-Uniqueness

**Comment by ghmcadams** [comment]
Covered by the GraphQL spec and therefore out of scope of this spec.
