### ISSUE TITLE
Find the best time for the GraphQL over HTTP working group

### ISSUE THREAD

**Issue by sjparsons** [graphql/graphql-over-http#115]
Hello, we'd like to make sure that we're meeting at the best time possible for all folks. If you're interested in participating, please fill out this doodle with the best time for you on the last Tuesday of every month (Tuesday being defined at 00:00 to 23:59 in UTC). I've picked July 28 (next day we'll meet) for the poll, but we'll use this time going forward for every last Tuesday of the month.

https://doodle.com/poll/2rwvachend53zism

@abernix @balshor @benjie @deinok @erikwittern @jaydenseric @michaelstaib @mike-marcacci @mmatsa @sjparsons @spawnia @sungam3r @enisdenjo

**Comment by benjie** [comment]
Sam I'm not sure the doodle is configured to do what you want it to do? I think you need to separately add 1 or 2 hour slots to it so we can check the slots we can attend.

**Comment by sjparsons** [comment]
You're right, @benjie. I've updated the link to 2 hour slots covering that same time period. Let me know if that doesn't work.

**Comment by sjparsons** [comment]
Just a quick reminder folks: please fill out the doodle link above with your availability so that we can get the best time to meet going forward. 

@abernix @balshor @benjie @deinok @ErikWittern @jaydenseric @michaelstaib @mike-marcacci @mmatsa @sjparsons @spawnia @sungam3r @enisdenjo

**Comment by michaelstaib** [comment]
Will do tonight, thanks for the ping 😅

**Comment by jaydenseric** [comment]
What is the time of the meeting? It's currently midnight Melbourne, Australia time and I need to know what time to set my wake-up alarm to. If a time is not apparent within the hour, I might sleep until ~8am local time.

**Comment by benjie** [comment]
I think we'll have to delay the meeting, I don't think a time was agreed.

**Comment by spawnia** [comment]
@sjparsons can you make a new poll for the August meeting?

**Comment by sjparsons** [comment]
@spawnia thanks for the reminder. I'm closing this issue to reduce confusion and will open another.
