### ISSUE TITLE
Migration to GraphQL Foundation

### ISSUE THREAD

**Issue by sjparsons** [graphql/graphql-over-http#117]
Acceptance Criteria:

* Official, legal adoption of the in progress GraphQL over HTTP spec into the GraphQL Foundation
* Migration of the repo into the GraphQL Foundation Github organization

This is a major step for us to make toward the 1.0 release. 

This issue will track the status of this work until it's complete.

**Comment by sjparsons** [comment]
Status: We have a tentative green light to do our work under the coverage of the GraphQL foundation:

> Hi Sam,
> 
> Sorry for the delay.  I talked this over with legal, and they suggested that this can be done under the existing graphql spec.  This is likely the best outcome, because it means there don't need to be multiple docs and signatures to participate; existing participants would be covered under their existing agreement.
>
> I think from that perspective, the next step is to begin work.  Does that make sense?
>
> Best,
> Brian

I'm inquiring whether this implies we have the green light to start migrating the repo into the GraphQL Foundation Github organization.

**Comment by IvanGoncharov** [comment]
Migrated 🎉
