### ISSUE TITLE
Make GraphQL MIME-type required

### ISSUE THREAD

**Issue by sjparsons** [graphql/graphql-over-http#118]
Document the agreement that we should require MIME-type, making all existing servers non-compliant. Update the intention of the 1.0 release to reflect the new approach to the spec.

**Comment by ghmcadams** [comment]
Addressed in recent changes to the spec

**Comment by benjie** [comment]
(This decision was reverted, but we're introducing a watershed on 1st Jan 2025 where support for the GraphQL MIME-type will be required.)
