### ISSUE TITLE
Pre-spec state and adoption guide

### ISSUE THREAD

**Issue by sjparsons** [graphql/graphql-over-http#119]
We would like to have a pre-spec state and an adoption guide to be release with the 1.0 version of the spec. We'll be releasing some breaking changes and we want to make it clear what implementors will need to do to become compliant. 

Tasks:
* Begin file to document the pre-spec state and adoption guide. Include draft structure and preamble
* ... brainstorm how to make this a reality

**Comment by ghmcadams** [comment]
I feel this has been addressed in recent changes to the spec
