### ISSUE TITLE
How to identify GraphQL requests

### ISSUE THREAD

**Issue by sjparsons** [graphql/graphql-over-http#120]
How can the server recognize the client sent a GraphQL Request? Clarify that part in the spec.

**Comment by mmatsa** [comment]
I think I can write a first draft for this, after the next mtg.

**Comment by sjparsons** [comment]
@mmatsa might be worth reading this PR and seeing whether there's some overlap. https://github.com/graphql/graphql-over-http/pull/83

**Comment by kettanaito** [comment]
As per the current state of the spec, the server can recognize a client request as a GraphQL request by the `Content-Type` header value. It should equal `application/graphql+json` if the request is intended to be handled as a GraphQL request.

**Comment by spawnia** [comment]
I think this issue can be closed, as https://github.com/graphql/graphql-over-http/pull/161 is merged.

**Comment by sungam3r** [comment]
> As per the current state of the spec, the server can recognize a client request as a GraphQL request by the Content-Type header value. It should equal application/graphql+json if the request is intended to be handled as a GraphQL request.

Things changed. Now server should deal with `Accept` header. No `application/graphql+json` mime for requests anymore, `application/graphql-response+json` only for responses.

**Comment by kettanaito** [comment]
Oh, that's useful! Thanks, @sungam3r.

To recap, is this the expected transaction?

```
Request:
POST /graphql
Accept: application/graphql-response+json
Content-Type: application/json // still need to describe sent body

Response:
200 OK /graphql
Content-Type: application/graphql-response+json
```

**Comment by benjie** [comment]
@kettanaito That's the intention after the watershed, but before then very few servers are likely to support it.

**Comment by Shane32** [comment]
The server may respond with `Content-Type: application/graphql-response+json; charset=utf-8`

See: https://github.com/graphql/graphql-over-http/blob/main/spec/GraphQLOverHTTP.md#media-types

**Comment by Shane32** [comment]
(For GraphQL.NET Server 7.1, released a few days ago, that is the default response content type, but the server will honor recognized ‘Accept’ headers.)

**Comment by benjie** [comment]
In the mean time, it

> is RECOMMENDED that a client set the Accept header to `application/graphql-response+json; charset=utf-8, application/json; charset=utf-8`.
> -- https://graphql.github.io/graphql-over-http/draft/#sel-EALHLDFAADHCA_zQ

This should maximize compatibility. If you want to use `@stream`/`@defer` then things get a little more complex...
