### ISSUE TITLE
Consider dropping GraphQL via GET (at least for Mutations)

### ISSUE THREAD

**Issue by andimarek** [graphql/graphql-over-http#123]
GraphQL Mutations via GET is very problematic: it goes against the fundamental idea of HTTP GET. It also has security implications: https://github.com/graphql-java/graphql-java-spring/issues/28#issue-569867780

I would recommend to drop HTTP via GET completely or move it to an optional recommendation with a clear explanation about the potential consequences.

**Comment by spawnia** [comment]
To be clear: Are you recommending to remove sending GraphQL Query operations through GET, too?

**Comment by andimarek** [comment]
Query is unfortunately a very overloaded term: the problem are not queries which are only reading, but the problem are queries which change something (mutations).

**Comment by spawnia** [comment]
> Query is unfortunately a very overloaded term.

I am aware, that is why I specifically alluded to *query operations* as opposed to *mutation operations*.

**Comment by andimarek** [comment]
@spawnia I agree that dropping GraphQL mutations only is theoretical option. Not sure this is good practical option as it requires a level of understanding of the query which is normally not available in the transport layer (the query must be parsed in order to say it is a query or mutation).

I amended the title to make it more clear.

**Comment by benjie** [comment]
In PostGraphile's server, we do the parsing in the server (and validation, for that matter), before later handing off to execute (`import { execute } from 'graphql'`) with the parsed document (AST). For a GraphQL server I think it's not unreasonable to expect the server to do superficial parsing of the document sufficient to determine the operation type; but maybe we could limit this requirement to only servers supporting `GET`?

I 100% agree that mutations **MUST NOT** be available over `GET`. I know there are people doing this currently, that's not sufficient to justify allowing it to me.

**Comment by andimarek** [comment]
I would recommend to make it optional at least: all GraphQL servers in production I know about don't support GET and only POST.  
Parsing and validating a Mutation via GET before it is rejected is doable of course, but this extra effort should be optional at least.

**Comment by jaydenseric** [comment]
The Apollo Client `HttpLink` already opts mutations out of GET requests:

https://github.com/apollographql/apollo-client/blob/287aa465d56fea7d2171533921e73b78caac26a7/src/link/http/createHttpLink.ts#L99-L104

**Comment by benjie** [comment]
Please raise that as a separate issue so it can be assigned to a milestone and discussed.
