### ISSUE TITLE
Cancelled: July working group meeting

### ISSUE THREAD

**Issue by sjparsons** [graphql/graphql-over-http#128]
Hello folks, I'm cancelling the July working group meeting today since I hadn't had a chance to work through the responses and communicate a new time. We will meet again on last Tuesday of August; later today I'll work through and communicate the responses about times. Apologies for the late notice. 

@abernix @balshor @benjie @deinok @erikwittern @jaydenseric @michaelstaib @mike-marcacci @mmatsa @sjparsons @spawnia @sungam3r @enisdenjo

Hat-tip @benjie for keeping me honest.

**Comment by benjie** [comment]
Credit to @jaydenseric; I just pinged a different channel (Slack) ;)
