### ISSUE TITLE
25 August 2020 - working group meeting

### ISSUE THREAD

**Issue by sjparsons** [graphql/graphql-over-http#132]
Hello, just opening a discussion to remind interested devs about our working group meeting on Tuesday, August 25th. Please see the agenda and open a PR to add yourself. Note we are meeting at the time we've met at before, 1900 UTC. Feel free to add a topic if you'd like to discuss timing again.

https://github.com/APIs-guru/graphql-over-http/blob/master/working-group/agendas/2020-08-25.md

@abernix @balshor @benjie @deinok @ErikWittern @jaydenseric @michaelstaib @mike-marcacci @mmatsa @sjparsons @spawnia @sungam3r @enisdenjo @IvanGoncharov

**Comment by spawnia** [comment]
Something came up, I can not fully join this time. Maybe I will be able to hop in for a few minutes to discuss https://github.com/graphql/graphql-over-http/pull/79.

@sjparsons could you bring up https://github.com/graphql/graphql-over-http/pull/79 as a talking point anyways? I incorporated the feedback from the last meeting and shrunk the PR to have minimal changes.

**Comment by sjparsons** [comment]
@spawnia Yup, I'm happy to do that

**Comment by benjie** [comment]
Sorry I missed it; life got hectic :sweat_smile:
