### ISSUE TITLE
ietf spec submission?

### ISSUE THREAD

**Issue by acao** [graphql/graphql-over-http#155]
Should we start submitting our transport spec to `ietf`? And how? I've never done this before

**Comment by mmatsa** [comment]
@acao Do you mean submitting the proposed new `application/graphql+json`?
I think @IvanGoncharov knows more about that process.
Note it's in https://github.com/graphql/graphql-over-http/pull/83/files but hasn't made it to the main branch yet.  We can try to get that merged.

**Comment by acao** [comment]
@mmatsa good question! the entire GraphQLOverHttp spec is what i’m thinking of, yes. Just saw that it’s stage 0 still, and this PR you mention, so perhaps its a bit early in this spec to start sending it off to the IETF just yet, but thats up to us when we would like to submit our first IETF RFC. 

It may broaden the peer review network to our RFC work, especially to those who live & breathe HTTP specs (CDN folks, browser folks, tooling maintainers, etc). especially with multipart coming up, we’ve already encountered integration issues with express-graphql and netlify functions, for example.

**Comment by benjie** [comment]
This was discussed at the GraphQL Spec WG a good while back and we decided to hold off on doing so.

(Incidentally, submitting to a standards body requires approval from the TSC.)

**Comment by ghmcadams** [comment]
Question was asked and answered.
