### ISSUE TITLE
Next meeting - Monday 27th June, 17:00 UTC?

### ISSUE THREAD

**Issue by benjie** [graphql/graphql-over-http#177]
~~May I suggest [Thursday 21st July at 15:00 UTC](https://www.timeanddate.com/worldclock/meetingdetails.html?year=2022&month=7&day=21&hour=15&min=0&sec=0&p1=3775&p2=110&p3=24&p4=37&p5=188&p6=496&p7=676&p8=438&p9=268&p10=234&p11=78&p12=604) as our next GraphQL-over-HTTP working group?~~

~~How about [Monday 27th June at 15:00 UTC](
https://www.timeanddate.com/worldclock/meetingdetails.html?year=2022&month=6&day=27&hour=15&min=0&sec=0&p1=3775&p2=110&p3=24&p4=37&p5=188&p6=496&p7=676&p8=438&p9=268&p10=234&p11=78&p12=604)?~~

[Monday 27th June at 17:00 UTC](https://www.timeanddate.com/worldclock/meetingdetails.html?year=2022&month=6&day=27&hour=17&min=0&sec=0&p1=3775&p2=110&p3=24&p4=37&p5=188&p6=496&p7=676&p8=438&p9=268&p10=234&p11=78&p12=604)?

cc @ghmcadams @spawnia @michaelstaib @glasser

**Comment by benjie** [comment]
How about [Monday 27th June at 15:00 UTC](
https://www.timeanddate.com/worldclock/meetingdetails.html?year=2022&month=6&day=27&hour=15&min=0&sec=0&p1=3775&p2=110&p3=24&p4=37&p5=188&p6=496&p7=676&p8=438&p9=268&p10=234&p11=78&p12=604)?

**Comment by spawnia** [comment]
I could do [Monday 27th June at 17:00 UTC](https://www.timeanddate.com/worldclock/meetingdetails.html?year=2022&month=6&day=27&hour=17&min=0&sec=0&p1=3775&p2=110&p3=24&p4=37&p5=188&p6=496&p7=676&p8=438&p9=268&p10=234&p11=78&p12=604).

**Comment by benjie** [comment]
I can make that work. If @michaelstaib can make it too, let's do it 👍

**Comment by michaelstaib** [comment]
Let's do it 😅

**Comment by glasser** [comment]
I am unlikely to have availability until July 6th, if having me there is helpful.

**Comment by benjie** [comment]
It would be great to have you attend; hopefully we can set up a regular schedule that everyone can make - if there's some general times you can/can't do it would be helpful if you could share them 👍
