### ISSUE TITLE
Next meeting: Thurs July 21st 17:00 UTC?

### ISSUE THREAD

**Issue by benjie** [graphql/graphql-over-http#184]
Posting from my phone; let me know if this time/date works for you and I’ll do the regular agenda stuff/etc during the week

@ghmcadams @spawnia @enisdenjo @glasser

**Comment by enisdenjo** [comment]
Works for me.

**Comment by michaelstaib** [comment]
Works for me.

**Comment by glasser** [comment]
Works for me.

**Comment by ghmcadams** [comment]
Works for me

**Comment by benjie** [comment]
Agenda created; please add yourselves (and any specific topics - feel free to add them above my topic which is basically an "everything else" topic :wink:)

**Comment by glasser** [comment]
My apologies -- I was only looking at my work calendar and missed a medical appointment at precisely the meeting time. I won't be able to attend this week.

**Comment by benjie** [comment]
@glasser If we were to delay it a couple hours, would you be able to make it then? (If so, what time?)

**Comment by glasser** [comment]
I'm not sure how long the appointment will be but two hours later should work. I can also do the preceding or following day at the same time. Sorry for not seeing this during the original scheduling process.

**Comment by michaelstaib** [comment]
I am ok with that

**Comment by glasser** [comment]
sorry, how do I join?
