### ISSUE TITLE
Response status code as `application/json` content

### ISSUE THREAD

**Issue by TomokiMiyauci** [graphql/graphql-over-http#203]
from https://graphql.github.io/graphql-over-http/draft/#sec-application-json

> application/json
> If the GraphQL response contains a non-null data entry then the server MUST use the 200 status code.

As an `application/json` content, if the `data` entry is `null` or none, what is the appropriate response status code?

**Comment by spawnia** [comment]
In that case, the first rule of the section applies:

> The server SHOULD use the 200 status code, independent of any [GraphQL request error](https://spec.graphql.org/draft/#sec-Errors.Request-errors) or [GraphQL field error](https://spec.graphql.org/draft/#sec-Errors.Field-errors) raised.

**Comment by TomokiMiyauci** [comment]
@spawnia Thanks for letting me know.

**Comment by TomokiMiyauci** [comment]
For the record, I understood the following.

Response status

|                                | application/graphql+json | application/json |
| ------------------------------ | ------------------------ | ---------------- |
| HTTP Request error             | 4XX(eg.406, 415)         | 4XX              |
| GraphQL request error          | 400                      | 200              |
| GraphQL field error            | 200                      | 200              |
| Unknown(Internal server) error | 5XX                      | 5XX              |
