### ISSUE TITLE
Kitchen sink HTTP requests

### ISSUE THREAD

**Issue by tobias-tengler** [graphql/graphql-over-http#228]
Would it make sense to create a collection of HTTP requests that represent common combinations of header values, validation failures, etc. and their expected status code / response headers according to this specification?

I'm thinking of either a collection of cURL scripts or an executable that you could point towards a GraphQL HTTP endpoint and assert that it is handling the cases described by the spec correctly.

Server maintainers could transfer these cases to their integration test sweet and other folk could use it to test an existing server for compliance.

I don't think it makes sense for every server maintainer to come up with all of the possible cases to test (especially with backwards compatibility), when there could be a programming language agnostic test suite as reference.

**Comment by spawnia** [comment]
There have been multiple discussions and proposals of how a test suite for spec complicance could look like. For instance, there is this issue which proposes extending express-graphql: https://github.com/graphql/graphql-over-http/issues/114.

I also gathered feedback from the working group on how a test suite could look like in https://github.com/graphql/graphql-over-http/issues/57#issuecomment-1191867161.

**Comment by enisdenjo** [comment]
[graphql-http](https://github.com/enisdenjo/graphql-http) contains a [suite of tests](https://github.com/enisdenjo/graphql-http/blob/master/src/audits/server.ts) to audit a server and check the compliance. You can integrate it into your test runner as simple as [this](https://github.com/dotansimha/graphql-yoga/blob/v3/packages/graphql-yoga/__tests__/graphql-http.spec.ts). 

Also worth mentioning, a few implementations are already tested in the repo and you can see their reports [here](https://github.com/enisdenjo/graphql-http/tree/master/implementations).
