### ISSUE TITLE
What is well-formed response

### ISSUE THREAD

**Issue by TomokiMiyauci** [graphql/graphql-over-http#230]
> When a server receives a GraphQL-over-HTTP request, it must return a well-formed response.

> In case of errors that completely prevent the generation of a well-formed GraphQL response, the server SHOULD respond with the appropriate status code depending on the concrete error condition.

What is the difference between a well-formed response and a well-formed GraphQL response?

As I understand it, a Well-formed GraphQL response is a JSON serialization with `data`, `errors` or `extensions` as keys. 

For example, if the client's "Accept" header is `text/*`, it has chosen to return a `406` status code.

Should the response body in this case be a JSON serialization with `errros` as the key?

**Comment by spawnia** [comment]
I see how the specification is unclear in its current form, the link for `GraphQL Response` should point to another URL. See https://github.com/graphql/graphql-over-http/pull/231#discussion_r993170327.

**Comment by ghmcadams** [comment]
@TomokiMiyauci Thank you for raising this issue.  #231 has been merged.  Do you believe it resolves this issue?

**Comment by TomokiMiyauci** [comment]
@ghmcadams Resolved. Thank you.
