### ISSUE TITLE
[2024-01-25] Contact Apollo about persisted operations appendix

### ISSUE THREAD

**Issue by benjie** [graphql/graphql-over-http#287]
Jovi is keen to advance the persisted operations proposal in #253; it is understood that Apollo may have concerns regarding their current implementation, so Jovi will reach out to understand the specific concerns.

- assignee(s): @JoviDeCroock 
- source: https://github.com/graphql/graphql-over-http/blob/main/working-group/notes/2024/2024-01.md#adding-a-section-on-security-concerns-30m-benjie

---

_Note: Action Item issues are reviewed and closed during Working Group
meetings._

**Comment by benjie** [comment]
@JoviDeCroock Please reply to this issue so that I can assign you.

**Comment by JoviDeCroock** [comment]
Hey! All right, I have reached out already over Twitter and hoping to find the folks closest to this that way
