### ISSUE TITLE
What is the rationale for handling Invalid parameters as 400?

### ISSUE THREAD

**Issue by wheresrhys** [graphql/graphql-over-http#288]
It feels quite unintuitive to me and my team that `Invalid parameters` is a 400 whereas most other 'bad requests' e.g. Document parsing failure are 200s.

> The server SHOULD use the 200 status code for every response to a well-formed GraphQL-over-HTTP request

From digging through the spec I can see

> Note: An HTTP request that encodes parameters of the same names but of the wrong type, or that omits required parameters, is not a well-formed GraphQL-over-HTTP request.

So I guess my question is equivalent to asking why this is not considered well-formed when so many other varieties of 'bad request' are? The GraphQL spec doesn't really make any distinction along these lines; it's just a [single concept of valid vs invalid](https://spec.graphql.org/June2018/#sec-Validating-Requests)

**Comment by benjie** [comment]
> It feels quite unintuitive to me and my team that Invalid parameters is a 400 whereas most other 'bad requests' e.g. Document parsing failure are 200s.

You appear to be talking about the legacy `application/json` content type. Your question relates to when the request doesn't look like a GraphQL request at all, we can't be sure that it is one - it's too corrupt/wrong/unintelligible. As such, we leave it up to you to determine what to do with the caveat that it shouldn't be a 2xx to make it clear to the client that the request has _not_ been interpretted as a GraphQL request. In all other situations we know it's a GraphQL request even if it's a bad one (invalid document, bad variables, etc), so we can respond with a GraphQL response.

For the client to be able to trust the response is a GraphQL response (as opposed to a response coming from an intermediary, such as a proxy server/cloudflare/etc), it _either_ needs to come back with a 200 status code (which proxy servers shouldn't corrupt) _or_ it needs something else to indicate it's definitely a GraphQL response. In the GraphQL-over-HTTP spec we use the `application/graphql-response+json` content type for this. If you're using this new content-type then you can use the various status codes detailed in that part of the spec: https://graphql.github.io/graphql-over-http/draft/#sec-application-graphql-response-json, e.g. 4xx or 5xx for responses where no `data` key is present (which would occur if request validation failed, or if variable coercion failed, to name a couple of scenarios).

**Comment by wheresrhys** [comment]
Yes I'm referring to the legacy `application/json` docs. In that section of the spec  it says

> Invalid parameters
> For example a POST request body of {"qeury": "{__typename}"} (note: typo) or {"query": "query Q ($i:Int!) { q(i: $i) }", "variables": [7]} (note: invalid shape for variables).
> A request that does not constitute a well-formed GraphQL-over-HTTP request SHOULD result in status code 400 (Bad Request).

This is the 'bad variables' case that you describe in your answer, and which you say should be a 2xx, which contradicts the spec, which says it should be a 400.

> doesn't look like a GraphQL request at all

I don't think this is true. The invalidity of the parameters can only be deduced by first parsing a valid GraphQL query document, so the request does at least partially look like a GraphQL request.

**Comment by Shane32** [comment]
> > doesn't look like a GraphQL request at all
> 
> I don't think this is true. The invalidity of the parameters can only be deduced by first parsing a valid GraphQL query document, so the request does at least partially look like a GraphQL request.

I think it will depend on the language in use.  For GraphQL.NET, attempting to deserialize a request with an array for `variables` will throw an exception within the deserializer.  So essentially, it might as well be garbage text; it can't proceed any further.  If it tried to deserialize a request with `qeury` instead of `query`, it wouldn't crash the deserializer, but would skip the property, so `query` would be null.  It would also be a request that could not be executed since there is no document to execute.  Either way, the error would occur within the GraphQL-over-HTTP layer, before reaching the GraphQL engine, and so it would return a 400 error since it could not attempt to execute the request, regardless of anything inside the GraphQL spec.

However, an implementation in Node or another language might behave differently.

**Comment by wheresrhys** [comment]
The implementation I have is node ([graphql-yoga](https://www.npmjs.com/package/graphql-yoga)).

To be clear, I'm not talking about requests that have absolute junk in variables, such as a badly formed json object - it's good data, but it just does not match the expectations of variables that the query document specifies. Here's an example of a request that is leading to a 400:

```JSON
{ 
  "query": "query($codes: [String!]) { systems (where: {code_IN: $codes}) { code }	}",
  "codes": [ null ]
}
```
The issue is that `null` is passed in in a non-nullable variable. Is it not the case that this error happens inside the GraphQL layer?

**Comment by Shane32** [comment]
Both of these are "well-formed requests", noting that the first has an unknown property that is ignored during deserialization.

```json
{ 
  "query": "query($codes: [String!]) { systems (where: {code_IN: $codes}) { code }	}",
  "codes": [ null ]
}
```

```json
{ 
  "query": "query($codes: [String!]) { systems (where: {code_IN: $codes}) { code }	}",
  "variables" : { "codes": [ null ] }
}
```

As these are well-formed requests, these errors occur during validation according to the main GraphQL spec.  The current GraphQL-over-HTTP draft spec indicates that for `application/json` responses to well-formed requests [which attempt to be executed] it should return 200 so it is known that the response is a GraphQL response.

**Comment by Shane32** [comment]
There exists a note as follows in the draft spec:

> Note: So long as it is a string, {query} does not have to parse or validate to be part of a well-formed GraphQL-over-HTTP request.

Perhaps it would be clearer if there was also a note stating:

> Note: So long as it is a map, {variables} does not have to validate to be part of a well-formed GraphQL-over-HTTP request.

**Comment by wheresrhys** [comment]
Thanks for the thorough explanation. I think I have 1 bit of feedback for the spec

In the example 'Invalid parameters' it's not clear that this refers specifically to the top level shape of the parameters (array not map). It'd be good to split into 2 examples: invalid top-level shape resulting in a 400, vs not conforming to the query document's expectations, resulting in a 200. At the moment the catch all heading "Invalid parameters" is ambiguous, and could be used to describe both scenarios, when the correct behaviour for each scenario is different.  Perhaps this lies behind graphql-yoga implementing the unintuitive behaviour it has.

And something like your suggested comment above woudl also be good 👍

**Comment by benjie** [comment]
> It'd be good to split into 2 examples: invalid top-level shape resulting in a 400, vs not conforming to the query document's expectations

We already have two examples along those lines, the first addresses when the parameters to the request are invalid:

https://graphql.github.io/graphql-over-http/draft/#sec-application-json.Examples.Invalid-parameters

The term "parameters" having been described previously in the spec (https://graphql.github.io/graphql-over-http/draft/#sec-Request-Parameters) - namely:

- `query` - Required, string
- `operationName` - Optional, string
- `variables` - Optional, map
- `extensions` - Optional, map

We also have an example that addresses variable coercion failure, which confirms you should get a 200 status code if the variables map cannot be coerced according to the rules of the GraphQL specification w.r.t. the GraphQL request you have encoded:

https://graphql.github.io/graphql-over-http/draft/#sec-application-json.Examples.Variable-coercion-failure

**Comment by wheresrhys** [comment]
Could the CoerceVariables example contain a concrete example? Many of the other examples do, and it would make it easier to recognise when a request falls into this category

**Comment by benjie** [comment]
Absolutely; please feel free to submit a PR! If you hover over the spec text a little GitHub icon should appear; click that to go to the file in question (and, in fact, the lines) and then click the edit pen icon at the top right to start making changes - GitHub should guide you through the process from there.

**Comment by wheresrhys** [comment]
@benjie graphql-yoga (where I first came across the erroneous 400 behaviour) [say they are compliant with the graphql-http test suite](https://github.com/dotansimha/graphql-yoga/issues/3178#issuecomment-1931819253), so I wonder if there is a mistake in that?

**Comment by Shane32** [comment]
The spec only says that 200 “SHOULD” be returned for application/json response types; it’s not an absolute requirement. Doesn’t that mean it could still be in compliance if it returns 400 (for responses with a null data field)?

**Comment by benjie** [comment]
@Shane32 the very next paragraph is:

> If the [GraphQL response](https://spec.graphql.org/draft/#sec-Response) contains a non-null data entry then the server MUST use the 200 status code.

**Comment by benjie** [comment]
Yes; it’s not forbidden to use 400 here since the application/json spec captured the state of the landscape rather than introducing new rules; that’s one reason why we have the new media type. However as it says: 400 should not be used because it means clients cannot trust the response.

**Comment by wheresrhys** [comment]
Thanks for the clarification
