### ISSUE TITLE
Define behavior of a shorthand query document and a specified operationName

### ISSUE THREAD

**Issue by Ethan-Arrowood** [graphql/graphql-over-http#312]
Apologies if this has already been discussed, but I'm trying to understand a certain edge case behavior. 

Considering a shorthand query document:

```graphql
{
  name
  breed
}
```

Combined with a `operationName` of `'Dog'`...

```curl
fetch('localhost/graphql', {
  method: 'POST',
  body: JSON.stringify({
    query: '{ name breed }',
    operationName: 'Dog'
  }),
});
```

Would this be considered equivalent to a named query? 

```graphql
{
  Dog {
    name
    breed
  }
}
```

**Comment by Shane32** [comment]
See https://spec.graphql.org/October2021/#sec-Executing-Requests :

> - If operationName is null:
>   - If document contains exactly one operation.
>     - Return the Operation contained in the document.
>   - Otherwise raise a request error requiring operationName.
> - Otherwise:
>    - Let operation be the Operation named operationName in document.
>    - If operation was not found, raise a request error.
>    - Return operation.

**Comment by Ethan-Arrowood** [comment]
Yeah just got to that part of the spec now. Seems like this line specifically is the answer to my question:

> If operation was not found, raise a request error.

[link](https://spec.graphql.org/draft/#sel-IANNHCDBDCAACEBkyM)
