### ISSUE TITLE
Action from Feb 25 meeting - GraphiQL

### ISSUE THREAD

**Issue by benjie** [graphql/graphql-over-http#70]
I think @jaydenseric (?) mentioned issues integrating GraphiQL into the test suite (?). I've spoken with @acao and they would like to help with guidance/etc - could someone please expand on what the issues are/what help is needed? Feel free to move this to the relevant repository. Thanks!

_Question marks are because I'm fried, and not confident I have the details right (and our live notes don't help)_

**Comment by benjie** [comment]
Closing as probably no longer relevant.

**Comment by jaydenseric** [comment]
Thanks for kicking this off, in the end after laying down the [`graphql-http-test`](https://github.com/jaydenseric/graphql-http-test) JS API and CLI there wasn't much time to deep dive into a GraphiQL integration, although that may change in the future!

Initially I did investigate creating a GraphiQL plugin, but got pretty confused about how that might work; it seems the API is in a state of change for [a future GraphiQL v1 release](https://github.com/graphql/graphiql/milestone/1).

If someone close to GraphiQL has any tips about how a possible integration might work, I'm all ears :)

**Comment by benjie** [comment]
What do you have in mind for a GraphiQL integration? Could you describe your ideal-world scenario?

**Comment by jaydenseric** [comment]
One idea was an "Audits" tab, like in the Chrome inspector. There you can click to run the GraphQL HTTP tests, and see a score/report. Individual tests that fail will have a description linking to the relevant parts of the spec, and a button to click that loads the query and arguments used in the test in the main GraphiQL panes, for the user to experiment with directly.

Another spin on this idea is a plugin that is not specifically for the GraphQL HTTP tests, but allows users to create their own suites of tests that can be run on demand. Individual tests would specify:

- Test name
- Markdown test description
- Query
- Variables
- Request headers
- Expected response headers
- Expected response payload
- Etc.

The GraphQL HTTP tests would then just be a particular set of sharable tests that run via this generic plugin.

**Comment by sungam3r** [comment]
> One idea was an "Audits" tab, like in the Chrome inspector. There you can click to run the GraphQL HTTP tests, and see a score/report. Individual tests that fail will have a description linking to the relevant parts of the spec, and a button to click that loads the query and arguments used in the test in the main GraphiQL panes, for the user to experiment with directly.

👍

**Comment by jaydenseric** [comment]
Really, there are two audiences that will benefit from HTTP testing:

1. People testing a published GraphQL server package or a GraphQL API, e.g. in CI. They will get a lot of benefit from a CLI tool like [`graphql-http-test`](https://github.com/jaydenseric/graphql-http-test).
2. Public users of GraphQL APIs that would like to be able to independently verify what they are dealing with. They will get a lot of use out of a GraphiQL audit feature.

Potentially the tests can be the same in both situations, but maybe more can be done in the CLI since it has the ability to load a custom schema + resolvers for the tests.

**Comment by benjie** [comment]
Sounds compelling. We should definitely wait for the GraphiQL plugin system to be in place before we attempt building this, but if anyone fancies building some mock-ups/wireframes that'd be really helpful.

**Comment by ghmcadams** [comment]
@benjie is this still relevant?

**Comment by benjie** [comment]
I think it's compelling, but I also think that it probably falls somewhat outside of the scope for which this subcommittee is responsible, so I think we should close it. Would be great to see it surface as a separate project though!
