### ISSUE TITLE
Adopt spec-md

### ISSUE THREAD

**Issue by leebyron** [graphql/graphql-over-http#8]
Use https://spec-md.com/ to format the GraphQL over HTTP spec. 

* This includes taking the README.md and transforming it into the right format needed for spec-md
* There may be a build step needed as a part of this work with Github Actions

(Edited on 7/1 with more info)

**Comment by IvanGoncharov** [comment]
Definitely something we need to do before public release 👍 
If someone wants to work on this, just claim this issue by leaving a comment.
It would also make sense to move spec into `graphql-over-http.md` file.

**Comment by spawnia** [comment]
https://spec-md.com/

**Comment by mmatsa** [comment]
@IvanGoncharov I plan to do the part of converting to spec-md (with neither content nor editorial edits) and pushing a PR, and would probably leave the automation to you as you offered at the meeting.

**Comment by sjparsons** [comment]
Would like to add some additional verbiage like, "spec is subject to change", before we publish this. Other than that we can get this published.

**Comment by ghmcadams** [comment]
Adopted in #122
