### ISSUE TITLE
Sub-Spec Limitations?

### ISSUE THREAD

**Issue by ghmcadams** [graphql/graphql-over-http#91]
I think we need to answer the question: Does `GraphQL over HTTP` describe:

1. An HTTP server with the singular purpose of handling GraphQL requests
2. The GraphQL endpoint of an HTTP server which may or may not handle other types of requests
3. The GraphQL requests and responses which are part of an HTTP server that handles GraphQL requests, but may also handle other types of requests (which GraphQL may or not be part of)

For number 3:
- how do we distinguish between GraphQL and non-GraphQL requests?
    - endpoint path?
    - content-type (for GET and POST requests?)
    - both?
- Are GraphQL responses allowed to be combined with or transformed into something that is no longer governed by this sub-spec?
- What kind of preprocessing is allowed by the server for GraphQL requests?

**Comment by spawnia** [comment]
The current spec text answers this question, albeit a bit vaguely.

> A GraphQL server operates on a single URL and all GraphQL requests for a given service should be directed at this URL. Other protocols may also use that URL.

I think that we are somewhere inbetween option 2 and 3 (Hint: 2 currently shows as 12, formatting is borked). It is crucial we clarify this part.

> how do we distinguish between GraphQL and non-GraphQL requests?

That's a question we must answer.

One part of the definition is that the server must designate a particular URL to handling GraphQL requests. That already rules out 1. and also opens up flexibility, e.g. a single server with multiple schemas/endpoints. 1 endpoint on a server = 1 GraphQL server.

The other part is that we have to define which requests to that endpoint must be interpreted as GraphQL and answered accordingly.

**Comment by ghmcadams** [comment]
Thanks, @spawnia.  I fixed the formatting.

I agree that we are between 2 and 3, though it feels to me that the current text implies number 1.  If the `server` operates on a single URL (endpoint) and all GraphQL requests should be directed to that URL, then there is effectively only one endpoint and all traffic goes there.

**Comment by spawnia** [comment]
I think that *directed* is meant to say that clients should send their requests to that endpoint, not that the server should magically redirect all GraphQL requests there.

That said, all the more reason to clarify that section of the spec.

**Comment by spawnia** [comment]
I have written up a clarification of what i think are the minimal requirements and the reasoning behind it.
